version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .

    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"

    links:
      - postgres

    volumes:
      - ./src/:/project/src/
      - ./backups:/backups

    command: /project/bin/uwsgi.sh

  postgres:
    env_file: .env
    image: postgres:9.5

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
